api_platform:
    title: 'Hair salon management CRUD APIs'
    description: 'CRUD API operations for managing hair salons'
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    # swagger:
    #     api_keys:
    #     JWT:
    #         name: Authorization
    #         type: header